# Generated by Django 5.1.3 on 2025-01-07 09:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userauthentication_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthentication',
            name='id',
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
