# Generated by Django 5.1.3 on 2025-01-07 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_userauthentication_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='user_id',
            field=models.AutoField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
