# Generated by Django 5.1.3 on 2025-02-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_userauthentication_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
