# Generated by Django 5.1.3 on 2025-02-15 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_userauthentication_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthentication',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
