# Generated by Django 5.1.3 on 2024-12-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
