# Generated by Django 5.1.3 on 2025-02-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='user_id',
            new_name='user',
        ),
    ]
