# Generated by Django 5.1.3 on 2025-02-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlocation',
            table='user_location_detail',
        ),
    ]
