# Generated by Django 5.1.6 on 2025-03-09 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_authentication', '0006_userauthentication_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_authentication.userauthentication')),
                ('front_side', models.ImageField(upload_to='documents/front_side/')),
                ('back_side', models.ImageField(upload_to='documents/back_side/')),
                ('profile', models.ImageField(upload_to='documents/profile_photos/')),
            ],
            options={
                'db_table': 'user_document_detail',
            },
        ),
    ]
